name: '🚀 Deploy to GitHub Pages'
description: 'Downloads build artifact and deploys it to GitHub Pages'
inputs:
  github_token:
    description: 'GitHub token for deployment'
    required: true
outputs:
  page_url:
    description: 'URL of the deployed GitHub Pages site'
    value: ${{ steps.gh_pages.outputs.page_url }}
runs:
  using: 'composite'
  steps:
    # Deploy the site to GitHub Pages
    - name: 🚀 Deploy to GitHub Pages
      id: gh_pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ inputs.github_token }}
        artifact_name: github-pages
