# .github/workflows/create-release.yml
##
# Create a new release
##
# This workflow builds the site and creates a new GitHub release.
# It can be triggered manually via workflow_dispatch.
#
# Required Settings:
#   - Actions Permissions -> Workflow Permissions
#     - Set to "Read and write permissions" for the workflow to create releases
#
# Optional Variables (Settings → Secrets and variables → Actions → Variables):
#   - BUILD_COMMAND: The npm command to run for building the site (defaults to "npm run build")
#
# To set these up:
#   1. Go to your GitHub repository
#   2. Navigate to Settings → Secrets and variables → Actions
#   4. Add the optional variables in the "Variables" tab
##

name: 📦 Create Release
run-name: create-release

on:
  workflow_dispatch:
  # deployment: # Uncomment this line to trigger on deployments

env:
  environment: production
  build_command: ${{ vars.BUILD_COMMAND || 'npm run build' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Build the site
      - name: 👷‍♂️ Build the site
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_command: ${{ env.build_command }}

  release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        # Checkout the repository
        - name: 📥 Checkout Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        # Create a new release
        - name: 📦 Create Release
          uses: ./.github/actions/new-release
          with:
            environment: ${{ env.environment }}
            ref: ${{ github.sha }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
